// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpiceFlow_Stock_Manager.Services;

#nullable disable

namespace SpiceFlow_Stock_Manager.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SpiceFlow_Stock_Manager.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ETA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.HasIndex("SpiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ETA = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpiceId = 1,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ETA = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpiceId = 3,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            ETA = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpiceId = 2,
                            UserId = 3
                        },
                        new
                        {
                            OrderId = 4,
                            ETA = new DateTime(2025, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpiceId = 4,
                            UserId = 4
                        },
                        new
                        {
                            OrderId = 5,
                            ETA = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderDate = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SpiceId = 5,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("SpiceFlow_Stock_Manager.Entities.Spice", b =>
                {
                    b.Property<int>("SpiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScovilleRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpiceId");

                    b.ToTable("Spices");

                    b.HasData(
                        new
                        {
                            SpiceId = 1,
                            ExpiryDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.imgur.com/beHWs9b.jpeg",
                            Origin = "Mexico",
                            Price = 15,
                            Sales = 75,
                            ScovilleRating = 100000,
                            SpiceName = "Habanero",
                            Stock = 150
                        },
                        new
                        {
                            SpiceId = 2,
                            ExpiryDate = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.imgur.com/8NQXwNE.jpeg",
                            Origin = "Mexico",
                            Price = 0,
                            Sales = 120,
                            ScovilleRating = 8000,
                            SpiceName = "Jalapeno",
                            Stock = 300
                        },
                        new
                        {
                            SpiceId = 3,
                            ExpiryDate = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.imgur.com/OxvJXwy.jpeg",
                            Origin = "India",
                            Price = 14,
                            Sales = 30,
                            ScovilleRating = 1000000,
                            SpiceName = "Ghost Pepper",
                            Stock = 50
                        },
                        new
                        {
                            SpiceId = 4,
                            ExpiryDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.imgur.com/QaeGKvO.jpeg",
                            Origin = "French Guiana",
                            Price = 9,
                            Sales = 90,
                            ScovilleRating = 50000,
                            SpiceName = "Cayenne",
                            Stock = 200
                        },
                        new
                        {
                            SpiceId = 5,
                            ExpiryDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://i.imgur.com/wcnPUFM.jpeg",
                            Origin = "Mexico",
                            Price = 8,
                            Sales = 60,
                            ScovilleRating = 2500,
                            SpiceName = "Serrano",
                            Stock = 180
                        });
                });

            modelBuilder.Entity("SpiceFlow_Stock_Manager.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Spice St, Flavor Town",
                            Cart = "",
                            Email = "spicelover99@hotmail.com",
                            IsManager = false,
                            Password = "1234",
                            PhoneNumber = "555-123-2020",
                            PostalCode = "L2D 3D1",
                            UserName = "spicelover99"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Heat Ave, Spice City",
                            Cart = "",
                            Email = "pepperenjoyer@gmail.com",
                            IsManager = false,
                            Password = "1234",
                            PhoneNumber = "647-090-2383",
                            PostalCode = "R3C 8N9",
                            UserName = "pepperenjoyer"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 Fire Blvd, Pepperville",
                            Cart = "",
                            Email = "heatfanatic@hotmail.com",
                            IsManager = false,
                            Password = "1234",
                            PhoneNumber = "401-398-3874",
                            PostalCode = "U2C 9A7",
                            UserName = "heatfan"
                        },
                        new
                        {
                            UserId = 4,
                            Address = "321 Flame Rd, Chili Town",
                            Cart = "",
                            Email = "spicyguy@spicemail.ca",
                            IsManager = false,
                            Password = "1234",
                            PhoneNumber = "212-932-5294",
                            PostalCode = "X8N 6F5",
                            UserName = "spiceman"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "654 Zest Ln, Aroma City",
                            Cart = "",
                            Email = "zestfest@mail.ca",
                            IsManager = false,
                            Password = "1234",
                            PhoneNumber = "901-219-7391",
                            PostalCode = "Z1Z 2M3",
                            UserName = "saffronman"
                        });
                });

            modelBuilder.Entity("SpiceFlow_Stock_Manager.Entities.Order", b =>
                {
                    b.HasOne("SpiceFlow_Stock_Manager.Entities.Spice", "Spice")
                        .WithMany()
                        .HasForeignKey("SpiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpiceFlow_Stock_Manager.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spice");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
